version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-config:/usr/local/etc/redis
    environment:
      REDIS_REPLICATION_MODE: master
    networks:
      - local-network
    restart: unless-stopped
#---------------------------------------------------------------------------------------------------------------------
networks:
  local-network:
    name: sample-network.local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.28.0.0/16
#---------------------------------------------------------------------------------------------------------------------
volumes:
  redis-data:
  redis-config:
